spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  cors:
    allowed-methods: ${ALLOWED_METHODS}
    allowed-origins: ${ALLOWED_ORIGINS}

  cookie:
    max-age: 1234567890
    path: /
    same-site: Lax
    secure: false
    http-only: true

  datasource:
    url: ${H2_DATABASE_URL}
    username: ${H2_DATABASE_USERNAME}
    password: ${H2_DATABASE_PASSWORD}
    driver-class-name: org.h2.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

security:
  jwt:
    secret-key: afdakfjlkasjfaioefjklasfmakl;fjaklfmakl;dfaklfadsflka
    access-expired: 987654321
    refresh-expired: 987654321

logging:
  level:
    org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket-name: ${S3_BUCKET_NAME}
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
      region: ${S3_REGION}
      image-url: ${S3_IMAGE_URL}