name: 배포 실패 알림

on:
  workflow_run:
    workflows: [ "백엔드 DEV CD" ]
    types:
      - completed

jobs:
  notify-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: 배포 실패 디스코드 알림
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"${{ secrets.DISCORD_NOTICE_MESSAGE }}\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
